### ISSUE TITLE
Can not init  GCKMediaMetadata with key

### ISSUE THREAD

**Issue by bishalg** [googlecast/CastVideos-ios#26]
I am using the GoogleCastSDK inside my Framework Target ( using as an Umbrella Framework)  , hence maybe I am facing issue using the Constant at runtime "**kGCKMetadataKeyTitle**". That is why I used string @"**kGCKMetadataKeyTitle**".

Q1. The following code is not return instance of  **GCKMediaMetadata** ( i.e it is nil ) ?
```
GCKMediaMetadata *metadata = [[GCKMediaMetadata alloc] initWithMetadataType:GCKMediaMetadataTypeMovie];
[metadata setString:@"Movie Title" forKey:@"kGCKMetadataKeyTitle"];
```
So can I use other string instead of static string given by SDK ?

I am trying to create _GCKMediaInformation_ following the documentation - 
[GCKMediaInformation](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_media_information)

Q2. Which of the fields of _GCKMediaInformation_ are optional and which are not, as I am getting nil for following code .
```
GCKMediaInformation *info = [[GCKMediaInformation alloc] initWithContentID: contentID
             streamType: streamType
             contentType: contentType
             metadata: metadata
             streamDuration: streamDuration
             mediaTracks: nil
             textTrackStyle: textTrackStyle
             customData: nil]; 
``` 
So of-course as metadata is nil, maybe MediaInformation will be nil, but that is not clearly mentioned on documentation which of the fields are required ?

**Comment by LeonNicholls** [comment]
Please take a look at this example:
https://developers.google.com/cast/docs/ios_sender_integrate#load_media

**Comment by bishalg** [comment]
@entertailion : thanks, I'm following the same documentation and tutorials.
But the major issue in documentation is, it does not mention which of the fields on `GCKMediaInformation` are compulsory and which are not to successfully initialize the class.

**Comment by LeonNicholls** [comment]
OK. Will raise this with engineering.

**Comment by LeonNicholls** [comment]
Everything that's marked as _nullable in GCKMediaInformation initializer is an optional field.

There's a bug in your code though. Instead of:
[metadata setString:@"Movie Title" forKey:@"kGCKMetadataKeyTitle"];
it should be:
[metadata setString:@"Movie Title" forKey:kGCKMetadataKeyTitle];

GCKMediaInformation does not require a non-nil metadata object. GCKMediaMetadata does not require any specific set of keys to be initialized.

The following call should never return nil:
GCKMediaMetadata *metadata = [[GCKMediaMetadata alloc] initWithMetadataType:GCKMediaMetadataTypeMovie];
