### ISSUE TITLE
Mini Controls crash in iOS 13 beta

### ISSUE THREAD

**Issue by aharriscrowne** [googlecast/CastVideos-ios#72]
Only workaround is to remove controls from project.

**Comment by Aurnax** [comment]
I think this is the same issue that I have. I get the error:
'<GCKUIButtonBarViewController: 0x13fd5f730> returned nil from -traitCollection, which is not allowed.'

**Comment by dhanmoti-infinit** [comment]
same here.
'<GCKUIButtonBarViewController: 0x7fa2e0a29b20> returned nil from -traitCollection, which is not allowed.'

**Comment by jtromo** [comment]
Are you seeing this in the sample? The sample has been updated to support iOS 13. Please test with the latest version of the sample and SDK and reopen this issue if it is still present. 

If the issue is not related to the sample, please file an issue here: https://developers.google.com/cast/support#report_issues

**Comment by travisbader** [comment]
After a bunch of changing code to try and isolate this issue, I found that a simple clean and re-build fixed this issue after changing simulator targets
